/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ffb4aa",
        "primary-container": "#e30613",
        "primary-fixed": "#ffdad5",
        "error": "#ba1a1a",
        "surface-container": "#edeef0",
        "on-tertiary-fixed": "#001b3c",
        "primary-fixed-dim": "#ffb4aa",
        "inverse-surface": "#2e3132",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-highest": "#e1e2e4",
        "surface-dim": "#d9dadc",
        "background": "#f8f9fb",
        "outline": "#936e69",
        "tertiary-fixed": "#d5e3ff",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-low": "#f3f4f6",
        "surface-variant": "#e1e2e4",
        "surface-tint": "#c0000c",
        "surface-bright": "#f8f9fb",
        "on-surface-variant": "#5e3f3b",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#f5f7ff",
        "surface": "#f8f9fb",
        "secondary-container": "#e4e2e1",
        "tertiary-container": "#0071d4",
        "inverse-on-surface": "#f0f1f3",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#a7c8ff",
        "on-secondary-container": "#656464",
        "tertiary": "#0059a8",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#930007",
        "secondary-fixed": "#e4e2e1",
        "on-primary-container": "#fff5f3",
        "surface-container-high": "#e7e8ea",
        "surface-container-lowest": "#ffffff",
        "primary": "#b5000b",
        "secondary": "#5f5e5e",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004788",
        "on-primary-fixed": "#410001",
        "outline-variant": "#e9bcb6",
        "accent": "#E30613", // Custom brand red
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "full": "0.75rem"
      },
    }
  },
  plugins: [],
}
